spring.datasource.url=jdbc:postgresql://db.sluqasoeqwykhvfqsmni.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=jas0988461867
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
line.scope=openid profile email
app.frontend-callback-url=http://localhost:5180/FurnitureRecycling_Frontend/line-callback
# For ngrok frontend testing, use:
# app.frontend-callback-url=https://unsocializable-darron-unmissed.ngrok-free.dev/line-callback
