# --- App ---
spring.application.name=FurnitureRecycling

# --- DataSource (Supabase / Postgres) ---
spring.datasource.url=jdbc:postgresql://db.sluqasoeqwykhvfqsmni.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=jas0988461867

#????????? Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# ????????????????
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
# ???????? schema??????spring.jpa.generate-ddl=false

# --- Logging (???? SQL ????) ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# --- Mail (???????/??) ---
# spring.mail.host=smtp.example.com
# spring.mail.port=587
# spring.mail.username=your-email@example.com
# spring.mail.password=your-email-password

# --- Flyway (?????) ---
spring.flyway.enabled=false



# ??????
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# ??? Hibernate ???? SQL ????
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

